/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Password */
        post: operations["change_password_api_v1_auth_change_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/attendance-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Attendance */
        get: operations["my_attendance_api_v1_me_attendance_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Statistics */
        get: operations["my_statistics_api_v1_me_statistics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/face/enrollment-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Enrollment */
        post: operations["create_enrollment_api_v1_face_enrollment_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/face/enrollment-sessions/{enrollment_id}/frames": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Enrollment Frames */
        post: operations["add_enrollment_frames_api_v1_face_enrollment_sessions__enrollment_id__frames_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/face/enrollment-sessions/{enrollment_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Enrollment */
        post: operations["submit_enrollment_api_v1_face_enrollment_sessions__enrollment_id__submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/face-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Face Profiles */
        get: operations["my_face_profiles_api_v1_me_face_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/face-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Face Profiles */
        get: operations["admin_face_profiles_api_v1_admin_face_profiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/face-profiles/{profile_id}/live-verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Live Verify Profile */
        post: operations["live_verify_profile_api_v1_admin_face_profiles__profile_id__live_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/face-profiles/{profile_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Profile */
        post: operations["approve_profile_api_v1_admin_face_profiles__profile_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/face-profiles/{profile_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Profile */
        post: operations["reject_profile_api_v1_admin_face_profiles__profile_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/face-profiles/{profile_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke Profile */
        post: operations["revoke_profile_api_v1_admin_face_profiles__profile_id__revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kiosk/device": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Device Status */
        get: operations["device_status_api_v1_kiosk_device_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kiosk/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kiosk Dashboard */
        get: operations["kiosk_dashboard_api_v1_kiosk_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kiosk/presence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kiosk Presence */
        get: operations["kiosk_presence_api_v1_kiosk_presence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kiosk/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kiosk Records */
        get: operations["kiosk_records_api_v1_kiosk_records_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kiosk/recognition-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Recognition Session */
        post: operations["create_recognition_session_api_v1_kiosk_recognition_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kiosk/recognition-sessions/{session_id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Recognition Session */
        post: operations["verify_recognition_session_api_v1_kiosk_recognition_sessions__session_id__verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kiosk/attendance-actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Attendance Action */
        post: operations["attendance_action_api_v1_kiosk_attendance_actions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v1_admin_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_api_v1_admin_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update User */
        patch: operations["update_user_api_v1_admin_users__user_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Password */
        post: operations["reset_password_api_v1_admin_users__user_id__reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Statistics */
        get: operations["statistics_api_v1_admin_statistics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/attendance-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Attendance */
        get: operations["list_attendance_api_v1_admin_attendance_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/attendance-sessions/{session_id}/correct": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Correct Attendance */
        post: operations["correct_attendance_api_v1_admin_attendance_sessions__session_id__correct_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/attendance-sessions/{session_id}/invalidate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invalidate Attendance */
        post: operations["invalidate_attendance_api_v1_admin_attendance_sessions__session_id__invalidate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/attendance-export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Attendance */
        get: operations["export_attendance_api_v1_admin_attendance_export_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Devices */
        get: operations["list_devices_api_v1_admin_devices_get"];
        put?: never;
        /** Create Device */
        post: operations["create_device_api_v1_admin_devices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/devices/bootstrap-local": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bootstrap Local Device
         * @description Create or repair the kiosk identity for the current browser installation.
         */
        post: operations["bootstrap_local_device_api_v1_admin_devices_bootstrap_local_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/devices/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Device */
        patch: operations["update_device_api_v1_admin_devices__device_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audit Logs */
        get: operations["list_audit_logs_api_v1_admin_audit_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminStatistics */
        AdminStatistics: {
            /** Current Count */
            current_count: number;
            /** Current Users */
            current_users: components["schemas"]["CurrentUserItem"][];
            /** Today Checkins */
            today_checkins: number;
            /** Today Checkouts */
            today_checkouts: number;
            /** Exception Count */
            exception_count: number;
            /** Daily */
            daily: components["schemas"]["DailyDuration"][];
            /** Ranking */
            ranking: components["schemas"]["RankingItem"][];
            /** Hourly */
            hourly: components["schemas"]["HourlyCount"][];
        };
        /**
         * AllowedAction
         * @enum {string}
         */
        AllowedAction: "CHECK_IN" | "CHECK_OUT" | "BLOCKED";
        /** AttendanceActionRequest */
        AttendanceActionRequest: {
            /** Ticket */
            ticket: string;
            action: components["schemas"]["AllowedAction"];
            /** Idempotency Key */
            idempotency_key: string;
        };
        /** AttendanceCorrection */
        AttendanceCorrection: {
            /**
             * Check Out At
             * Format: date-time
             */
            check_out_at: string;
            /** Reason */
            reason: string;
        };
        /** AttendanceInvalidate */
        AttendanceInvalidate: {
            /** Reason */
            reason: string;
        };
        /** AttendancePublic */
        AttendancePublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Check In At
             * Format: date-time
             */
            check_in_at: string;
            /** Check Out At */
            check_out_at: string | null;
            /** Duration Seconds */
            duration_seconds: number | null;
            status: components["schemas"]["AttendanceStatus"];
            /** Corrected */
            corrected: boolean;
            /** Correction Reason */
            correction_reason: string | null;
            /** User Name */
            user_name?: string | null;
            /** Username */
            username?: string | null;
        };
        /**
         * AttendanceStatus
         * @enum {string}
         */
        AttendanceStatus: "OPEN" | "CLOSED" | "MISSING_CHECKOUT" | "INVALID";
        /** AuditLogPublic */
        AuditLogPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Actor User Id */
            actor_user_id: string | null;
            /** Actor Device Id */
            actor_device_id: string | null;
            /** Action */
            action: string;
            /** Target Type */
            target_type: string;
            /** Target Id */
            target_id: string;
            /** Before Data */
            before_data: {
                [key: string]: unknown;
            } | null;
            /** After Data */
            after_data: {
                [key: string]: unknown;
            } | null;
            /** Reason */
            reason: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** Body_add_enrollment_frames_api_v1_face_enrollment_sessions__enrollment_id__frames_post */
        Body_add_enrollment_frames_api_v1_face_enrollment_sessions__enrollment_id__frames_post: {
            /** Files */
            files: string[];
        };
        /** Body_live_verify_profile_api_v1_admin_face_profiles__profile_id__live_verify_post */
        Body_live_verify_profile_api_v1_admin_face_profiles__profile_id__live_verify_post: {
            /** Files */
            files: string[];
        };
        /** Body_verify_recognition_session_api_v1_kiosk_recognition_sessions__session_id__verify_post */
        Body_verify_recognition_session_api_v1_kiosk_recognition_sessions__session_id__verify_post: {
            /** Files */
            files: string[];
        };
        /**
         * ChallengeType
         * @enum {string}
         */
        ChallengeType: "STATIC" | "TURN_LEFT" | "TURN_RIGHT";
        /** ChangePasswordRequest */
        ChangePasswordRequest: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** CurrentUserItem */
        CurrentUserItem: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Real Name */
            real_name: string;
            /** Username */
            username: string;
            /**
             * Check In At
             * Format: date-time
             */
            check_in_at: string;
        };
        /** DailyDuration */
        DailyDuration: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Duration Seconds */
            duration_seconds: number;
        };
        /** DeviceCreate */
        DeviceCreate: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Location */
            location: string;
        };
        /** DeviceCreated */
        DeviceCreated: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Location */
            location: string;
            /** Is Active */
            is_active: boolean;
            /** Last Seen At */
            last_seen_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Secret */
            secret: string;
        };
        /** DevicePublic */
        DevicePublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Location */
            location: string;
            /** Is Active */
            is_active: boolean;
            /** Last Seen At */
            last_seen_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** DeviceUpdate */
        DeviceUpdate: {
            /** Name */
            name?: string | null;
            /** Location */
            location?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** EnrollmentCreate */
        EnrollmentCreate: {
            /** Target User Id */
            target_user_id?: string | null;
            /** @default SELF */
            mode: components["schemas"]["EnrollmentMode"];
        };
        /**
         * EnrollmentMode
         * @enum {string}
         */
        EnrollmentMode: "SELF" | "ADMIN";
        /** EnrollmentPublic */
        EnrollmentPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Profile Id
             * Format: uuid
             */
            profile_id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            status: components["schemas"]["EnrollmentStatus"];
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * EnrollmentStatus
         * @enum {string}
         */
        EnrollmentStatus: "COLLECTING" | "SUBMITTED" | "COMPLETED" | "EXPIRED";
        /**
         * FaceBox
         * @description Face bounds normalized to the submitted frame dimensions.
         */
        FaceBox: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Width */
            width: number;
            /** Height */
            height: number;
        };
        /** FaceProfilePublic */
        FaceProfilePublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            status: components["schemas"]["FaceProfileStatus"];
            mode: components["schemas"]["EnrollmentMode"];
            /** Model Version */
            model_version: string;
            /** Quality Score */
            quality_score: number | null;
            /** Liveness Score */
            liveness_score: number | null;
            /** Live Verified At */
            live_verified_at: string | null;
            /** Rejection Reason */
            rejection_reason: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Submitted At */
            submitted_at: string | null;
            /** Reviewed At */
            reviewed_at: string | null;
            /**
             * Template Count
             * @default 0
             */
            template_count: number;
            /** User Name */
            user_name?: string | null;
            /** Username */
            username?: string | null;
        };
        /**
         * FaceProfileStatus
         * @enum {string}
         */
        FaceProfileStatus: "DRAFT" | "PENDING" | "ACTIVE" | "REJECTED" | "REPLACED" | "REVOKED";
        /** FrameProcessResponse */
        FrameProcessResponse: {
            /** Accepted */
            accepted: number;
            /** Rejected */
            rejected: number;
            /** Template Count */
            template_count: number;
            /** Average Quality */
            average_quality: number;
            /** Liveness Score */
            liveness_score: number;
            /** Messages */
            messages: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Database */
            database: string;
            /** Face Engine */
            face_engine: string;
            /**
             * Time
             * Format: date-time
             */
            time: string;
        };
        /** HourlyCount */
        HourlyCount: {
            /** Hour */
            hour: number;
            /** Count */
            count: number;
        };
        /** KioskDashboard */
        KioskDashboard: {
            device: components["schemas"]["DevicePublic"];
            /** Engine Status */
            engine_status: string;
            /** Engine Version */
            engine_version?: string | null;
            /**
             * Server Time
             * Format: date-time
             */
            server_time: string;
            /** Current Count */
            current_count: number;
            /** Today Checkins */
            today_checkins: number;
            /** Today Checkouts */
            today_checkouts: number;
            /** Exception Count */
            exception_count: number;
            /** Recent Records */
            recent_records: components["schemas"]["KioskRecordItem"][];
        };
        /** KioskPresencePage */
        KioskPresencePage: {
            /** Items */
            items: components["schemas"]["CurrentUserItem"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** KioskRecordItem */
        KioskRecordItem: {
            /** Id */
            id: string;
            /** Real Name */
            real_name?: string | null;
            action?: components["schemas"]["AllowedAction"] | null;
            /** Result */
            result: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
        };
        /** KioskRecordPage */
        KioskRecordPage: {
            /** Items */
            items: components["schemas"]["KioskRecordItem"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** LiveVerifyResponse */
        LiveVerifyResponse: {
            /** Verified */
            verified: boolean;
            /** Score */
            score: number;
            /** Threshold */
            threshold: number;
        };
        /** LocalDeviceBootstrap */
        LocalDeviceBootstrap: {
            /**
             * Installation Id
             * Format: uuid
             */
            installation_id: string;
            /**
             * Name
             * @default 本机打卡终端
             */
            name: string;
            /**
             * Location
             * @default 当前电脑
             */
            location: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** Message */
        Message: {
            /** Message */
            message: string;
        };
        /** Page[AttendancePublic] */
        Page_AttendancePublic_: {
            /** Items */
            items: components["schemas"]["AttendancePublic"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** Page[AuditLogPublic] */
        Page_AuditLogPublic_: {
            /** Items */
            items: components["schemas"]["AuditLogPublic"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** Page[FaceProfilePublic] */
        Page_FaceProfilePublic_: {
            /** Items */
            items: components["schemas"]["FaceProfilePublic"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** Page[UserPublic] */
        Page_UserPublic_: {
            /** Items */
            items: components["schemas"]["UserPublic"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** PasswordReset */
        PasswordReset: {
            /** New Password */
            new_password: string;
        };
        /** RankingItem */
        RankingItem: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Real Name */
            real_name: string;
            /** Username */
            username: string;
            /** Duration Seconds */
            duration_seconds: number;
            /** Checkin Count */
            checkin_count?: number;
            /** Checkout Count */
            checkout_count?: number;
            /** Is Active */
            is_active?: boolean;
        };
        /** RecognitionSessionPublic */
        RecognitionSessionPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            challenge: components["schemas"]["ChallengeType"];
            /** Prompt */
            prompt: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** RecognitionVerifyResponse */
        RecognitionVerifyResponse: {
            /** Recognized */
            recognized: boolean;
            /** User Id */
            user_id?: string | null;
            /** Real Name */
            real_name?: string | null;
            /** @default BLOCKED */
            allowed_action: components["schemas"]["AllowedAction"];
            /** Message */
            message: string;
            /** Ticket */
            ticket?: string | null;
            /** Match Score */
            match_score?: number | null;
            /** Liveness Score */
            liveness_score?: number | null;
            face_box?: components["schemas"]["FaceBox"] | null;
            /** Quality Hint */
            quality_hint?: string | null;
            /** Processing Ms */
            processing_ms?: number | null;
            /** Processed At */
            processed_at?: string | null;
        };
        /** RejectFaceRequest */
        RejectFaceRequest: {
            /** Reason */
            reason: string;
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "USER" | "ADMIN";
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
            user: components["schemas"]["UserPublic"];
        };
        /** UserCreate */
        UserCreate: {
            /** Username */
            username: string;
            /** Real Name */
            real_name: string;
            /** Identifier */
            identifier?: string | null;
            /** Password */
            password: string;
            /** @default USER */
            role: components["schemas"]["Role"];
        };
        /** UserPublic */
        UserPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Username */
            username: string;
            /** Real Name */
            real_name: string;
            /** Identifier */
            identifier: string | null;
            role: components["schemas"]["Role"];
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** UserStatistics */
        UserStatistics: {
            /** Today Seconds */
            today_seconds: number;
            /** Week Seconds */
            week_seconds: number;
            /** Month Seconds */
            month_seconds: number;
            /** Ongoing Since */
            ongoing_since: string | null;
            /** Ongoing Seconds */
            ongoing_seconds: number;
            /** Daily */
            daily: components["schemas"]["DailyDuration"][];
            /** Recent Sessions */
            recent_sessions: components["schemas"]["AttendancePublic"][];
        };
        /** UserUpdate */
        UserUpdate: {
            /** Real Name */
            real_name?: string | null;
            /** Identifier */
            identifier?: string | null;
            role?: components["schemas"]["Role"] | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                lab_refresh_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                lab_refresh_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
        };
    };
    change_password_api_v1_auth_change_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_attendance_api_v1_me_attendance_sessions_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["AttendanceStatus"] | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AttendancePublic_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_statistics_api_v1_me_statistics_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserStatistics"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_enrollment_api_v1_face_enrollment_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrollmentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_enrollment_frames_api_v1_face_enrollment_sessions__enrollment_id__frames_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                enrollment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_add_enrollment_frames_api_v1_face_enrollment_sessions__enrollment_id__frames_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameProcessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_enrollment_api_v1_face_enrollment_sessions__enrollment_id__submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                enrollment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FaceProfilePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_face_profiles_api_v1_me_face_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FaceProfilePublic"][];
                };
            };
        };
    };
    admin_face_profiles_api_v1_admin_face_profiles_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["FaceProfileStatus"] | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_FaceProfilePublic_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_verify_profile_api_v1_admin_face_profiles__profile_id__live_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_live_verify_profile_api_v1_admin_face_profiles__profile_id__live_verify_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveVerifyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_profile_api_v1_admin_face_profiles__profile_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FaceProfilePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_profile_api_v1_admin_face_profiles__profile_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectFaceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FaceProfilePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_profile_api_v1_admin_face_profiles__profile_id__revoke_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    device_status_api_v1_kiosk_device_get: {
        parameters: {
            query?: never;
            header: {
                "X-Device-Code": string;
                "X-Device-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevicePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kiosk_dashboard_api_v1_kiosk_dashboard_get: {
        parameters: {
            query?: never;
            header: {
                "X-Device-Code": string;
                "X-Device-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KioskDashboard"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kiosk_presence_api_v1_kiosk_presence_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header: {
                "X-Device-Code": string;
                "X-Device-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KioskPresencePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kiosk_records_api_v1_kiosk_records_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header: {
                "X-Device-Code": string;
                "X-Device-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KioskRecordPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_recognition_session_api_v1_kiosk_recognition_sessions_post: {
        parameters: {
            query?: never;
            header: {
                "X-Device-Code": string;
                "X-Device-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecognitionSessionPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_recognition_session_api_v1_kiosk_recognition_sessions__session_id__verify_post: {
        parameters: {
            query?: never;
            header: {
                "X-Device-Code": string;
                "X-Device-Key": string;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_verify_recognition_session_api_v1_kiosk_recognition_sessions__session_id__verify_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecognitionVerifyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    attendance_action_api_v1_kiosk_attendance_actions_post: {
        parameters: {
            query?: never;
            header: {
                "X-Device-Code": string;
                "X-Device-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttendanceActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendancePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_v1_admin_users_get: {
        parameters: {
            query?: {
                q?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_UserPublic_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_api_v1_admin_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_v1_admin_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_api_v1_admin_users__user_id__reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordReset"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    statistics_api_v1_admin_statistics_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStatistics"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_attendance_api_v1_admin_attendance_sessions_get: {
        parameters: {
            query?: {
                user_id?: string | null;
                status?: components["schemas"]["AttendanceStatus"] | null;
                start_at?: string | null;
                end_at?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AttendancePublic_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    correct_attendance_api_v1_admin_attendance_sessions__session_id__correct_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttendanceCorrection"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendancePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invalidate_attendance_api_v1_admin_attendance_sessions__session_id__invalidate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttendanceInvalidate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_attendance_api_v1_admin_attendance_export_csv_get: {
        parameters: {
            query?: {
                start_at?: string | null;
                end_at?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_devices_api_v1_admin_devices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevicePublic"][];
                };
            };
        };
    };
    create_device_api_v1_admin_devices_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bootstrap_local_device_api_v1_admin_devices_bootstrap_local_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocalDeviceBootstrap"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_device_api_v1_admin_devices__device_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevicePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_logs_api_v1_admin_audit_logs_get: {
        parameters: {
            query?: {
                action?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AuditLogPublic_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
